version: "3"
services:

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ucha
      MYSQL_DATABASE: gestion-alimentos
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080